spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: MICROSERVICE-ZUUL
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
  instance:
    instance-id: zuul9527
    prefer-ip-address: true
zuul:
  prefix: "/aigou"  #前缀
  ignored-services: "*" #不能直接用服务名访问
  routes:
    flat.serviceId: plat-service
    flat.path: /plat/**
    product.serviceId: product-service
    product.path: /product/**
    redis.serviceId: redis-privoder
    redis.path: /common/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

---
spring:
  profiles: dev1
  application:
    name: MICROSERVICE-ZUUL
server:
  port: 9528
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
  instance:
    instance-id: zuul9527
    prefer-ip-address: true
zuul:
  prefix: "/aigou"  #前缀
  ignored-services: "*" #不能直接用服务名访问
  routes:
    flat.serviceId: plat-service
    flat.path: /plat/**
